# Generated by Django 5.0.6 on 2024-06-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0004_oglasview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OglasView',
            new_name='Pregled',
        ),
    ]
