# Generated by Django 5.0.6 on 2024-06-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0005_rename_oglasview_pregled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pregled',
            unique_together=set(),
        ),
    ]
