# Generated by Django 5.0.6 on 2024-06-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0006_alter_pregled_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregled',
            options={'verbose_name': 'Pregled', 'verbose_name_plural': 'Pregledi'},
        ),
    ]
