# Generated by Django 5.0.6 on 2024-06-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0007_alter_pregled_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pregled',
            unique_together={('oglas', 'ip_address', 'timestamp')},
        ),
    ]
