# Generated by Django 5.0.6 on 2024-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0009_oglas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='status',
            field=models.CharField(choices=[('aktivan', 'Aktivan'), ('neaktivan', 'Neaktivan'), ('arhiviran', 'Arhiviran')], default='aktivan', max_length=10),
        ),
    ]
