# Generated by Django 5.0.6 on 2024-06-26 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0010_alter_oglas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
