# Generated by Django 5.0.6 on 2024-06-27 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0011_alter_oglas_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='napisani_komentari', to=settings.AUTH_USER_MODEL)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
